from polynomials.poly_methods import reduction
from polynomials.buchberger import buchberger

def ideal_membership(Poly_g, Poly_set_F):
    """Determines whether a polynomial is in the ideal generated by
    a finite list of polynomials.
    
    Arguments
    Poly_g -- an instance of Polynomial.
    Poly_set_F -- a list of non-zero Polynomial instances.
    
    Returns
    True if poly_g is in the ideal generated by Poly_set_F, else False."""

    Poly_set_G = buchberger(Poly_set_F)

    return reduction(Poly_g, Poly_set_G).is_zero